### ISSUE TITLE
[bug]播放中暂停，点击列表再返回播放器，页面播放状态消失

### ISSUE THREAD

**Issue by willerfu** [YMBo/react-music#1]
这个bug困惑着我，不知码主如何解决。

**Comment by YMBo** [comment]
不是有一个isPlay状态么，通过这个参数判断当前状态

**Comment by willerfu** [comment]
码主你有按照我说的试下不，我知道isPlay这个状态判断播放暂停。我说的情况是你音乐正在播放，你点击按键让它暂停时，isplay==false,此时音乐停止，然后你点击列表进入列表页，然后再点击浏览器返回键，返回到播放页，这时候原先播放的进度，时间线都会消失。

**Comment by YMBo** [comment]
恩 我明白了 现在问题已经解决了 主要是因为跳转回来后isPlay和进度条的进度状态没有保存，所以会导致这样的bug，代码已经提交，你可以参考下，[在线预览](https://ymbo.github.io/react-music/#/)

**Comment by YMBo** [comment]
刚刚我提交了两次，第一次是解决你说的那个bug，解决后会有新的bug，不过也不难，'暂停当前歌曲点击列表页别的歌曲再次返回时，按钮和封面状态不改变bug'  就是这个，解决办法是再次添加了一个订阅事件改变全局的isplay状态，你可以参考我的提交记录[在线预览](https://ymbo.github.io/react-music/#/)

**Comment by willerfu** [comment]
好的，回去试试
